[package]
name = "xiaomi_eu_toolkit_zygisk"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[lib]
name = "xiaomi_eu_toolkit_zygisk"
crate-type = ["cdylib"]

[dependencies]
android_logger = "0.15"
jni = "0.22"
log = "0.4"
zygisk-api = { git = "https://gitlab.com/magisk3171/zygisk-api-rs.git", tag = "v0.0.2" }

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
